/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betybatik.view;

import betybatik.engine.conn_service;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.out;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ANDITO
 */
public class FrmPemilikLihatBarang extends javax.swing.JFrame {

    /**
     * Creates new form FrmPemilikLihatBarang
     */
    public FrmPemilikLihatBarang() {
        initComponents();
        txtIdBarang.setEnabled(false);
        load_table();
        loadDiskon();
    }
 private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Stok");
        model.addColumn("Merk");
        model.addColumn("Ukuran");
        model.addColumn("Harga");
      try {
             int no=1;
            String sql = "select * from barang";//fungsi untuk mengambil data dari tabel barang
            java.sql.Connection conn=(Connection)conn_service.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});//fungsi untuk menambah data sesuai baris
            }
            tblPemilikBarang.setModel(model);
        } catch (Exception e) {
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemilikBarang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAturDiskon = new javax.swing.JTextField();
        btnUbahDiskon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPemilikBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPemilikBarang.getTableHeader().setReorderingAllowed(false);
        tblPemilikBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemilikBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemilikBarang);

        jLabel1.setText("Diskon");

        btnUbahDiskon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUbahDiskon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/03.png"))); // NOI18N
        btnUbahDiskon.setText("Ubah Diskon");
        btnUbahDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDiskonActionPerformed(evt);
            }
        });

        jLabel2.setText("IDBarang");

        jLabel3.setText("%");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/discount.png"))); // NOI18N

        txtDiskon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAturDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUbahDiskon)
                                .addGap(64, 64, 64))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAturDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(btnUbahDiskon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPemilikBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemilikBarangMouseClicked
        int baris = tblPemilikBarang.rowAtPoint(evt.getPoint());   
        String idbarang = tblPemilikBarang.getValueAt(baris, 1).toString();
        txtIdBarang.setText(idbarang);  // TODO add your handling code here:
        String diskon = tblPemilikBarang.getValueAt(0, 8).toString();
        txtAturDiskon.setText(diskon);  // TODO add your handling code here:
    }//GEN-LAST:event_tblPemilikBarangMouseClicked

    private void btnUbahDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDiskonActionPerformed
saveDiskon();
loadDiskon();
        /*
        try {
          //String sql ="UPDATE barang SET Kode_Barang = '"+"',diskon= '"+txtAturDiskon.getText()+"' WHERE Kode_Barang = '"+txtIdBarang.getText()+"'";
           String sql ="UPDATE barang SET Kode_Barang = '"+txtIdBarang.getText()+"',diskon= '"+txtAturDiskon.getText()+"' WHERE Kode_Barang = '"+txtIdBarang.getText()+"'";
            java.sql.Connection conn=(Connection)conn_service.configDB();//Fungsi update barang
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diskon diUpdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();//fungsi perbarui tabel setiap ada perubahan // TODO add your handling code here:
*/
    }//GEN-LAST:event_btnUbahDiskonActionPerformed

public void saveDiskon(){
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(".\\diskon.txt"));
                writer.write(txtAturDiskon.getText());
                writer.close();
                JOptionPane.showMessageDialog(null, "Done");
        } catch (IOException e) {
            e.printStackTrace();
        }}
public void loadDiskon(){
    try {
        FileReader fr = new FileReader(".\\diskon.txt");
        BufferedReader br = new BufferedReader(fr);
        
        String str;
        while((str = br.readLine()) != null){
        //out.println(str+"\n");
        txtDiskon.setText(str);
        }
        br.close();
    } catch (Exception e) {
        out.println("File not Found!");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPemilikLihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPemilikLihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPemilikLihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPemilikLihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPemilikLihatBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUbahDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPemilikBarang;
    private javax.swing.JTextField txtAturDiskon;
    private javax.swing.JLabel txtDiskon;
    private javax.swing.JTextField txtIdBarang;
    // End of variables declaration//GEN-END:variables
}
