/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betybatik.view;

/**
 *
 * @author ANDITO
 */
public class MainMenu_Admin extends javax.swing.JFrame {
    public MainMenu_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminGanti = new javax.swing.JButton();
        btnADataSupplier = new javax.swing.JButton();
        btnADataMember = new javax.swing.JButton();
        btnADataBarang = new javax.swing.JButton();
        btnADataKasir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdminGanti.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdminGanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/Log-Out-icon.png"))); // NOI18N
        btnAdminGanti.setText("Ganti Akun");
        btnAdminGanti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGantiActionPerformed(evt);
            }
        });

        btnADataSupplier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnADataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/lorrygreen.png"))); // NOI18N
        btnADataSupplier.setText("DATA SUPPLIER");
        btnADataSupplier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnADataSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnADataSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnADataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADataSupplierActionPerformed(evt);
            }
        });

        btnADataMember.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnADataMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/people3.png"))); // NOI18N
        btnADataMember.setText("DATA MEMBER");
        btnADataMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnADataMember.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnADataMember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnADataMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADataMemberActionPerformed(evt);
            }
        });

        btnADataBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnADataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/t_shirt.png"))); // NOI18N
        btnADataBarang.setText("DATA BARANG");
        btnADataBarang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnADataBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnADataBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnADataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADataBarangActionPerformed(evt);
            }
        });

        btnADataKasir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnADataKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betybatik/image/calculator.png"))); // NOI18N
        btnADataKasir.setText("DATA KASIR");
        btnADataKasir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnADataKasir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnADataKasir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnADataKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADataKasirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminGanti, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnADataSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnADataMember, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnADataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnADataKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminGanti, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnADataMember, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(btnADataKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnADataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnADataSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGantiActionPerformed
              new Login().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAdminGantiActionPerformed

    private void btnADataKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADataKasirActionPerformed
        new FrmAdminDataKasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnADataKasirActionPerformed

    private void btnADataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADataSupplierActionPerformed
       new FrmAdminDataSupplier().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnADataSupplierActionPerformed

    private void btnADataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADataMemberActionPerformed
       new FrmAdminDataMember().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnADataMemberActionPerformed

    private void btnADataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADataBarangActionPerformed
        new FrmAdminDataBarang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnADataBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADataBarang;
    private javax.swing.JButton btnADataKasir;
    private javax.swing.JButton btnADataMember;
    private javax.swing.JButton btnADataSupplier;
    private javax.swing.JButton btnAdminGanti;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
