CREATE DATABASE BETY_BATIK
USE BETY_BATIK

CREATE TABLE BARANG(
KODE_BARANG CHAR (5) PRIMARY KEY NOT NULL,
NAMA_BARANG VARCHAR(50) NOT NULL,
Jenis_BARANG VARCHAR(50) NOT NULL,
stok CHAR(13) NOT NULL,
merek VARCHAR(50) NOT NULL,
ukuran VARCHAR(10) NOT NULL,
HARGA NUMERIC(18,0)
)

CREATE TABLE kasir(
id_kasir CHAR (5) PRIMARY KEY NOT NULL,
NAMA_kasir VARCHAR(50) NOT NULL,
alamat_kasir VARCHAR(100) NOT NULL,
no_telp CHAR(13) NOT NULL
)

CREATE TABLE member(
id_member CHAR (5) PRIMARY KEY NOT NULL,
NAMA_member VARCHAR(50) NOT NULL,
alamat VARCHAR(100) NOT NULL,
no_hp CHAR(13) NOT NULL
)

CREATE TABLE supplier(
id_supplier CHAR (5) PRIMARY KEY NOT NULL,
NAMA_supplier VARCHAR(50) NOT NULL,
alamat VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL,
no_hp CHAR(13) NOT NULL
)

CREATE TABLE Penjualan(
KODE_Penjualan CHAR (10) PRIMARY KEY NOT NULL,
tanggal date NOT NULL,
NAMA_BARANG VARCHAR(50) NOT NULL,
Jenis_BARANG VARCHAR(50) NOT NULL,
diskon CHAR(10) ,
jumlah VARCHAR(10) NOT NULL,
id_kasir CHAR (5) NOT NULL FOREIGN KEY REFERENCES kasir (id_kasir),
id_member CHAR (5) NOT NULL FOREIGN KEY REFERENCES member (id_member)
)

CREATE TABLE Laporan(
KODE_Laporan CHAR (5) PRIMARY KEY NOT NULL,
jenis_Laporan VARCHAR(30) NOT NULL,
nama_Laporan VARCHAR(50) NOT NULL,
isi_Laporan VARCHAR(300) NOT NULL,
tanggal date NOT NULL,
kode_Penjualan CHAR (10) NOT NULL FOREIGN KEY REFERENCES penjualan (kode_Penjualan )
)

CREATE TABLE Pembelian(
KODE_Pembelian CHAR (10) PRIMARY KEY NOT NULL,
tanggal date NOT NULL,
id_supplier  CHAR (5) NOT NULL FOREIGN KEY REFERENCES supplier(id_supplier )
)

CREATE TABLE detailPenjualan(
KODE_DP CHAR (10) PRIMARY KEY NOT NULL,
jumlah NUMERIC (18,0) NOT NULL,
HARGA NUMERIC (18,0) NOT NULL,
kode_penjualan CHAR (10) NOT NULL FOREIGN KEY REFERENCES penjualan(kode_penjualan),
kode_barang CHAR (5) NOT NULL FOREIGN KEY REFERENCES barang (kode_barang)
)

CREATE TABLE detailPembelian(
KODE_DPembelian CHAR (10) PRIMARY KEY NOT NULL,
total NUMERIC (18,0) NOT NULL,
subtotal NUMERIC (18,0) NOT NULL,
hargabeli NUMERIC (18,0) NOT NULL,
kode_pembelian CHAR (10) NOT NULL FOREIGN KEY REFERENCES pembelian(kode_pembelian),
kode_barang CHAR (5) NOT NULL FOREIGN KEY REFERENCES barang (kode_barang)
)
